unishef: &unishef
  host: adldap.shef.ac.uk
  port: 636
  base: DC=shefuniad,DC=shef,DC=ac,DC=uk
  ssl: true

  attribute: sAMAccountName

  # Check the "AD LDAP - epiGenesys" note in LastPass for username and password
  username: CN=SoftwareHutLDAP,OU=ServiceAccounts,OU=Resources,DC=shefuniad,DC=shef,DC=ac,DC=uk
  password: g94jh@s7fsn4B.a]ghir

development:
  <<: *unishef

test:
  host: localhost
  port: 1389
  attribute: uid
  base: ou=Users
  ssl: false

qa:
  <<: *unishef

demo:
  <<: *unishef

production:
  <<: *unishef
